function [passed, lines] = testFourPieceMultiBoundary()
%TESTFOURPIECEMULTIBOUNDARY A 5000 nm segment crossing X, Y, then Z.

cfg.HALF_L = 5000;
cfg.L = 10000;
cfg.reconstructionTolerance = 1e-8;
dz = sqrt(5000^2 - 3000^2 - 3000^2);
originalStart = [4500 4000 3500];
originalEnd = originalStart + [3000 3000 dz];
wrapped = wrapSegmentToBox(originalStart, originalEnd, cfg.HALF_L, ...
    cfg.L, cfg.reconstructionTolerance);
[sequence, ~] = extractBoundaryEvents(wrapped.Translation, ...
    cfg.reconstructionTolerance);

expectedTranslation = [0 0 0; -10000 0 0; ...
    -10000 -10000 0; -10000 -10000 -10000];
inside = all(wrapped.Start(:) >= -cfg.HALF_L - 1e-6) && ...
    all(wrapped.Start(:) <= cfg.HALF_L + 1e-6) && ...
    all(wrapped.End(:) >= -cfg.HALF_L - 1e-6) && ...
    all(wrapped.End(:) <= cfg.HALF_L + 1e-6);
passed = size(wrapped.Start, 1) == 4 && strcmp(sequence, 'X>Y>Z') && ...
    max(abs(wrapped.Translation(:) - expectedTranslation(:))) <= 1e-6 && ...
    abs(sum(wrapped.Length) - 5000) <= 1e-6 && inside;
lines = {sprintf('4-Piece X>Y>Z boundary PASS=%d', passed)};
end
