function [valid, pieces, maximumConsistencyError] = ...
        forwardValidateEndpointCandidate(candidateStart, candidateEnd, ...
        wrappedP1, wrappedP2, cfg)
%FORWARDVALIDATEENDPOINTCANDIDATE Apply and audit the PDF boundary rule.

pieces = wrapSegmentToBox(candidateStart, candidateEnd, ...
    cfg.HALF_L, cfg.L, cfg.geometryTolerance);
inside = all(pieces.Start(:) >= -cfg.HALF_L - cfg.geometryTolerance) && ...
    all(pieces.Start(:) <= cfg.HALF_L + cfg.geometryTolerance) && ...
    all(pieces.End(:) >= -cfg.HALF_L - cfg.geometryTolerance) && ...
    all(pieces.End(:) <= cfg.HALF_L + cfg.geometryTolerance);
positive = all(pieces.Length > cfg.geometryTolerance);
lengthConserved = abs(sum(pieces.Length) - cfg.mediumALength) <= ...
    cfg.endpointLengthTolerance;
[startEquivalent, startError] = periodicPointEquivalent(candidateStart, ...
    wrappedP1, cfg.L, cfg.geometryTolerance);
[endEquivalent, endError] = periodicPointEquivalent(candidateEnd, ...
    wrappedP2, cfg.L, cfg.geometryTolerance);
maximumConsistencyError = max(startError, endError);
valid = inside && positive && lengthConserved && ...
    startEquivalent && endEquivalent;
end
