function names = paperFigureNames()
%PAPERFIGURENAMES Stable names for the ten required Q1 paper figures.

names = {'retained_part_inverse_principle', ...
    'single_boundary_real_examples', 'retained_model_status', ...
    'piece_count_distribution', 'charge_vs_conduction', ...
    'group1_upper_bound_certificate', 'q1_group1_3d', ...
    'q1_group2_3d', 'q1_group3_3d', 'q1_three_groups_overview'};
end
