function issueCount = runPaperFinalCheckcode(projectRoot, logPath)
%RUNPAPERFINALCHECKCODE Check the paper-final extension under R2016a.

files = { ...
    fullfile(projectRoot, 'src', 'buildGroup1OptimisticUpperBound.m'), ...
    fullfile(projectRoot, 'src', 'writePaperFinalOutputs.m'), ...
    fullfile(projectRoot, 'src', 'buildNaNSeparatedPolyline.m'), ...
    fullfile(projectRoot, 'src', 'generateOnePaperFigure.m'), ...
    fullfile(projectRoot, 'src', 'getChineseFontName.m'), ...
    fullfile(projectRoot, 'src', 'paperFigureNames.m'), ...
    fullfile(projectRoot, 'src', 'paperText.m'), ...
    fullfile(projectRoot, 'src', 'writeFigureManifest.m'), ...
    fullfile(projectRoot, 'src', 'runPaperFinalCheckcode.m'), ...
    fullfile(projectRoot, 'tests', 'testOptimisticUpperBound.m'), ...
    fullfile(projectRoot, 'scripts', 'run_q1_paper_compute.m'), ...
    fullfile(projectRoot, 'scripts', 'run_q1_paper_figures_safe.m'), ...
    fullfile(projectRoot, 'scripts', 'run_q1_paper_final.m')};
fileID = fopen(logPath, 'w');
if fileID < 0, error('runPaperFinalCheckcode:OpenFailed', ...
        'Cannot write %s.', logPath); end
cleanup = onCleanup(@() fclose(fileID));
issueCount = 0;
for fileIndex = 1:numel(files)
    messages = checkcode(files{fileIndex}, '-id');
    fprintf(fileID, 'FILE=%s ISSUES=%d\r\n', files{fileIndex}, numel(messages));
    issueCount = issueCount + numel(messages);
    for messageIndex = 1:numel(messages)
        message = messages(messageIndex);
        fprintf(fileID, '  line=%d id=%s message=%s\r\n', ...
            message.line, message.id, message.message);
    end
end
fprintf(fileID, 'TOTAL_ISSUES=%d\r\n', issueCount);
clear cleanup;
end
