function writeRetainedPartSummary(path, branchName, baseCommit, matlabVersion, ...
        groups, resultsByGroup, groupStats, modelComplete)
%WRITERETAINEDPARTSUMMARY Write the auditable retained-part result summary.

fileID = fopen(path, 'w');
if fileID < 0
    error('writeRetainedPartSummary:OpenFailed', 'Cannot write %s.', path);
end
cleanup = onCleanup(@() fclose(fileID));
fprintf(fileID, 'Q1 RETAINED ORIGINAL PART HYPOTHESIS\r\n');
fprintf(fileID, 'Branch=%s\r\nBaseCommit=%s\r\nMATLABVersion=%s\r\n', ...
    branchName, baseCommit, matlabVersion);
fprintf(fileID, 'Records=%d\r\n\r\n', sum([groupStats.Records]));

total = aggregate(groupStats);
printCounts(fileID, 'TOTAL', total);
for groupIndex = 1:3
    printCounts(fileID, sprintf('Group%d', groupIndex), groupStats(groupIndex));
end

fprintf(fileID, '\r\nQ1ModelComplete=%d\r\n', modelComplete);
for groupIndex = 1:3
    stats = groupStats(groupIndex);
    fprintf(fileID, ['Group%d UniqueOnlyConducting=%d FinalStatus=%s\r\n' ...
        'Group%d BFS=%s\r\n'], groupIndex, stats.UniqueOnlyConducting, ...
        stats.FinalStatus, groupIndex, stats.BFSPath);
end

fprintf(fileID, '\r\nREAL SINGLE-BOUNDARY REPLAY EXAMPLES\r\n');
for groupIndex = 1:3
    selected = 0;
    for mediumID = 1:numel(resultsByGroup{groupIndex})
        if strcmp(resultsByGroup{groupIndex}{mediumID}.Status, ...
                'RETAINED_SINGLE_BOUNDARY_UNIQUE')
            selected = mediumID;
            break;
        end
    end
    if selected == 0
        fprintf(fileID, 'Group%d: NONE\r\n', groupIndex);
        continue;
    end
    item = resultsByGroup{groupIndex}{selected};
    fprintf(fileID, ['Group%d A%d ExcelRow=%d\r\nObserved=%s -> %s\r\n' ...
        'Lobs=%.15g Lmiss=%.15g\r\nRecoveredOriginal=%s -> %s\r\n' ...
        'BoundarySequence=%s ForwardPieceCount=%d\r\n'], groupIndex, selected, ...
        groups(groupIndex).OriginalExcelRow(selected), ...
        vectorText(groups(groupIndex).P1(selected, :)), ...
        vectorText(groups(groupIndex).P2(selected, :)), item.RawLength, ...
        item.MissingLength, vectorText(item.ReconstructedOriginalStart), ...
        vectorText(item.ReconstructedOriginalEnd), ...
        item.BoundaryEventSequence, item.ForwardPieceCount);
    for pieceIndex = 1:item.ForwardPieceCount
        fprintf(fileID, '  P%d %s -> %s Translation=%s\r\n', pieceIndex, ...
            vectorText(item.ForwardPieces.Start(pieceIndex, :)), ...
            vectorText(item.ForwardPieces.End(pieceIndex, :)), ...
            vectorText(item.ForwardPieces.Translation(pieceIndex, :)));
    end
end
clear cleanup;
end

function printCounts(fileID, label, stats)
fprintf(fileID, ['%s Records=%d Direct5000=%d SingleBoundaryShort=%d ' ...
    'SingleBoundaryRecovered=%d SingleBoundaryReplayFailed=%d ' ...
    'TwoBoundaryShort=%d NoBoundaryShort=%d HasAbs500=%d ' ...
    'NoBoundaryHasAbs500=%d ' ...
    'Unique=%d Ambiguous=%d Unresolved=%d Invalid=%d\r\n'], ...
    label, stats.Records, stats.Direct, stats.SingleBoundaryShort, ...
    stats.SingleBoundaryRecovered, stats.ReplayFailed, ...
    stats.TwoBoundaryShort, stats.NoBoundaryShort, stats.HasAbs500, ...
    stats.NoBoundaryHasAbs500, stats.Unique, stats.Ambiguous, ...
    stats.Unresolved, stats.Invalid);
fprintf(fileID, '%s PieceCounts 1=%d 2=%d 3=%d 4=%d TotalPieces=%d\r\n', ...
    label, stats.PieceCountByMedium(1), stats.PieceCountByMedium(2), ...
    stats.PieceCountByMedium(3), stats.PieceCountByMedium(4), stats.TotalPieces);
end

function total = aggregate(stats)
names = {'Records','Direct','SingleBoundaryShort','SingleBoundaryRecovered', ...
    'ReplayFailed','TwoBoundaryShort','NoBoundaryShort','HasAbs500', ...
    'NoBoundaryHasAbs500', ...
    'Unique','Ambiguous','Unresolved','Invalid','TotalPieces'};
for index = 1:numel(names)
    total.(names{index}) = sum([stats.(names{index})]);
end
total.PieceCountByMedium = sum(vertcat(stats.PieceCountByMedium), 1);
end

function value = vectorText(vector)
value = sprintf('[%.15g %.15g %.15g]', vector(1), vector(2), vector(3));
end
