function writeEndpointRebuildTables(groups, analyses, relativeResults, ...
        explicitResults, consistencyByGroup, sensitivityRows, ...
        piecesByGroup, tableDir)
%WRITEENDPOINTREBUILDTABLES Write complete 729/27 endpoint audit tables.

fileID = openOutput(fullfile(tableDir, 'endpoint_pair_diagnostics.csv'));
fprintf(fileID, ['Group,MediumID,ExcelRow,X1WrappedX,X1WrappedY,' ...
    'X1WrappedZ,X2WrappedX,X2WrappedY,X2WrappedZ,RawDx,RawDy,RawDz,' ...
    'RawLength,n1x,n1y,n1z,n2x,n2y,n2z,X1CandidateX,X1CandidateY,' ...
    'X1CandidateZ,X2CandidateX,X2CandidateY,X2CandidateZ,' ...
    'CandidateLength,LengthError,Valid5000,RelativeKx,RelativeKy,' ...
    'RelativeKz,GeometryClassID\n']);
for groupIndex = 1:3
    for mediumID = 1:analyses{groupIndex}.Records
        explicit = explicitResults{groupIndex}{mediumID};
        relative = relativeResults{groupIndex}{mediumID};
        for row = 1:729
            fprintf(fileID, ['%d,A%d,%d,' repmat('%.15g,', 1, 24) ...
                '%d,%d,%d,%d,%d\n'], groupIndex, mediumID, ...
                groups(groupIndex).OriginalExcelRow(mediumID), ...
                groups(groupIndex).P1(mediumID, :), ...
                groups(groupIndex).P2(mediumID, :), ...
                relative.RawDelta, relative.RawLength, ...
                explicit.AllN1(row, :), explicit.AllN2(row, :), ...
                explicit.P1Candidate(row, :), explicit.P2Candidate(row, :), ...
                explicit.CandidateLength(row), explicit.LengthError(row), ...
                explicit.Valid5000(row), explicit.RelativeK(row, :), ...
                explicit.GeometryClassID(row));
        end
    end
end
fclose(fileID);

fileID = openOutput(fullfile(tableDir, ...
    'endpoint_relative_shift_diagnostics.csv'));
fprintf(fileID, ['Group,MediumID,ExcelRow,X1WrappedX,X1WrappedY,' ...
    'X1WrappedZ,X2WrappedX,X2WrappedY,X2WrappedZ,RawDx,RawDy,RawDz,' ...
    'RawLength,kx,ky,kz,RecoveredDx,RecoveredDy,RecoveredDz,' ...
    'RecoveredLength,LengthError,IsLengthCandidate,PhysicalCandidateID,' ...
    'PieceCount\n']);
for groupIndex = 1:3
    for mediumID = 1:analyses{groupIndex}.Records
        item = relativeResults{groupIndex}{mediumID};
        for row = 1:27
            fprintf(fileID, ['%d,A%d,%d,' repmat('%.15g,', 1, 18) ...
                '%d,%d,%d\n'], groupIndex, mediumID, ...
                groups(groupIndex).OriginalExcelRow(mediumID), ...
                groups(groupIndex).P1(mediumID, :), ...
                groups(groupIndex).P2(mediumID, :), item.RawDelta, ...
                item.RawLength, item.AllK(row, :), ...
                item.RecoveredDelta(row, :), item.RecoveredLength(row), ...
                item.LengthError(row), item.Valid5000(row), ...
                item.GeometryClassID(row), item.PieceCountByK(row));
        end
    end
end
fclose(fileID);

fileID = openOutput(fullfile(tableDir, 'endpoint_reconstruction_audit.csv'));
fprintf(fileID, ['Group,MediumID,ExcelRow,RawLength,Explicit729ValidCount,' ...
    'Relative27ValidCount,PhysicalCandidateCount,Status,SelectedKx,' ...
    'SelectedKy,SelectedKz,UnwrappedLength,PieceCount,' ...
    'BoundaryEventSequence,MaxConsistencyError,NearestKx,NearestKy,' ...
    'NearestKz,NearestLengthError\n']);
for groupIndex = 1:3
    for mediumID = 1:analyses{groupIndex}.Records
        item = relativeResults{groupIndex}{mediumID};
        explicit = explicitResults{groupIndex}{mediumID};
        [~, nearestRow] = min(abs(item.LengthError));
        if strcmp(item.Status, 'UNIQUE')
            selected = item.SelectedIndex;
            k = item.CandidatesK(selected, :);
            lengthValue = item.UnwrappedLength(selected);
            pieceCount = item.PieceCount(selected);
            sequence = item.BoundaryEventSequence{selected};
            consistencyError = item.MaxConsistencyError(selected);
        else
            k = [NaN NaN NaN]; lengthValue = NaN; pieceCount = 0;
            sequence = 'NOT_UNIQUE'; consistencyError = NaN;
        end
        fprintf(fileID, ['%d,A%d,%d,%.15g,%d,%d,%d,%s,' ...
            '%.15g,%.15g,%.15g,%.15g,%d,%s,%.15g,%d,%d,%d,%.15g\n'], ...
            groupIndex, mediumID, groups(groupIndex).OriginalExcelRow(mediumID), ...
            item.RawLength, explicit.ValidCandidateCount, ...
            item.MathematicalCandidateCount, item.PhysicalCandidateCount, ...
            item.Status, k, lengthValue, pieceCount, sequence, ...
            consistencyError, item.AllK(nearestRow, :), ...
            item.LengthError(nearestRow));
    end
end
fclose(fileID);

fileID = openOutput(fullfile(tableDir, 'endpoint_enumerator_consistency.csv'));
fprintf(fileID, ['Group,MediumID,ExplicitPhysicalCandidateCount,' ...
    'RelativePhysicalCandidateCount,SameGeometrySet,Pass\n']);
for groupIndex = 1:3
    for mediumID = 1:analyses{groupIndex}.Records
        explicit = explicitResults{groupIndex}{mediumID};
        relative = relativeResults{groupIndex}{mediumID};
        pass = consistencyByGroup{groupIndex}(mediumID);
        fprintf(fileID, '%d,A%d,%d,%d,%d,%d\n', groupIndex, mediumID, ...
            explicit.PhysicalCandidateCount, ...
            relative.PhysicalCandidateCount, pass, pass);
    end
end
fclose(fileID);

fileID = openOutput(fullfile(tableDir, 'tolerance_sensitivity.csv'));
fprintf(fileID, 'Group,Tolerance,Unique,AmbiguousPeriodic,Unresolved\n');
for row = 1:numel(sensitivityRows)
    item = sensitivityRows(row);
    fprintf(fileID, '%d,%.15g,%d,%d,%d\n', item.Group, ...
        item.Tolerance, item.Unique, item.AmbiguousPeriodic, item.Unresolved);
end
fclose(fileID);

writePieceTables(groups, relativeResults, piecesByGroup, tableDir);
end

function writePieceTables(groups, relativeResults, piecesByGroup, tableDir)
fileID = openOutput(fullfile(tableDir, 'reconstructed_pieces.csv'));
fprintf(fileID, ['Group,MediumID,PieceIndex,SourceExcelRow,' ...
    'WrappedInputP1X,WrappedInputP1Y,WrappedInputP1Z,WrappedInputP2X,' ...
    'WrappedInputP2Y,WrappedInputP2Z,UnwrappedStartX,UnwrappedStartY,' ...
    'UnwrappedStartZ,UnwrappedEndX,UnwrappedEndY,UnwrappedEndZ,' ...
    'RelativeShiftKx,RelativeShiftKy,RelativeShiftKz,PieceStartX,' ...
    'PieceStartY,PieceStartZ,PieceEndX,PieceEndY,PieceEndZ,PieceLength,' ...
    'TranslationX,TranslationY,TranslationZ,TStart,TEnd,' ...
    'BoundaryEventSequence\n']);
for groupIndex = 1:3
    pieces = piecesByGroup{groupIndex};
    for pieceIndex = 1:numel(pieces.MediumID)
        fprintf(fileID, ['%d,A%d,%d,%d,' repmat('%.15g,', 1, 27) '%s\n'], ...
            groupIndex, pieces.MediumID(pieceIndex), ...
            pieces.PieceIndex(pieceIndex), pieces.SourceExcelRow(pieceIndex), ...
            pieces.WrappedInputP1(pieceIndex, :), ...
            pieces.WrappedInputP2(pieceIndex, :), ...
            pieces.UnwrappedStart(pieceIndex, :), ...
            pieces.UnwrappedEnd(pieceIndex, :), ...
            pieces.RelativeShiftK(pieceIndex, :), ...
            pieces.PieceStart(pieceIndex, :), pieces.PieceEnd(pieceIndex, :), ...
            pieces.PieceLength(pieceIndex), pieces.Translation(pieceIndex, :), ...
            pieces.TStart(pieceIndex), pieces.TEnd(pieceIndex), ...
            pieces.BoundaryEventSequence{pieceIndex});
    end
end
fclose(fileID);

fileID = openOutput(fullfile(tableDir, 'piece_count_audit.csv'));
fprintf(fileID, ['Group,MediumID,ExcelRow,EndpointStatus,PieceCount,' ...
    'TotalPieceLength,BoundaryEventSequence\n']);
for groupIndex = 1:3
    pieces = piecesByGroup{groupIndex};
    for mediumID = 1:numel(relativeResults{groupIndex})
        item = relativeResults{groupIndex}{mediumID};
        indices = find(pieces.MediumID == mediumID);
        if strcmp(item.Status, 'UNIQUE')
            totalLength = sum(pieces.PieceLength(indices));
            sequence = item.BoundaryEventSequence{item.SelectedIndex};
        else
            totalLength = NaN; sequence = 'NOT_UNIQUE';
        end
        fprintf(fileID, '%d,A%d,%d,%s,%d,%.15g,%s\n', groupIndex, ...
            mediumID, groups(groupIndex).OriginalExcelRow(mediumID), ...
            item.Status, numel(indices), totalLength, sequence);
    end
end
fclose(fileID);
end

function fileID = openOutput(path)
fileID = fopen(path, 'w');
if fileID < 0
    error('writeEndpointRebuildTables:OpenFailed', 'Cannot write %s.', path);
end
end
